const STATES = {
  IDLE: "IDLE",
  AWAITING_SERVICE: "AWAITING_SERVICE",
  AWAITING_DATE: "AWAITING_DATE",
  AWAITING_CONFIRMATION: "AWAITING_CONFIRMATION",
};

const GLOBAL_COMMANDS = {
  MENU: "menu",
  CANCEL: "cancelar",
};

module.exports = {
  STATES,
  GLOBAL_COMMANDS,
};
